DROP TABLE IF EXISTS projects
CASCADE;
DROP TABLE IF EXISTS configurations
CASCADE;
DROP TABLE IF EXISTS themes
CASCADE;

CREATE TABLE projects
(
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  user_id TEXT NOT NULL,
  default_thumbnail TEXT NOT NULL DEFAULT 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTpu7CL3YZ2G5jL3nyW2CdsedQ6QumMLlzUqk8jdCghfPCqRSQr&usqp=CAU',
  model_link TEXT NOT NULL,
  created_at TIMESTAMP
  WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
  WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

  CREATE TABLE configurations
  (
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(255),
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    config_data TEXT,
    created_at TIMESTAMP
    WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
    WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

    CREATE TABLE themes
    (
      id SERIAL PRIMARY KEY NOT NULL,
      user_id VARCHAR(255) NOT NULL,
      theme VARCHAR(255) NOT NULL DEFAULT 'cherry'
    );